//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controladores.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string afip_certificado {
            get {
                return ((string)(this["afip_certificado"]));
            }
            set {
                this["afip_certificado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string afip_contrasenia {
            get {
                return ((string)(this["afip_contrasenia"]));
            }
            set {
                this["afip_contrasenia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string afip_cuitEmisor {
            get {
                return ((string)(this["afip_cuitEmisor"]));
            }
            set {
                this["afip_cuitEmisor"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_nombreEmpresa
        {
            get
            {
                return ((string)(this["pGeneral_nombreEmpresa"]));
            }
            set
            {
                this["pGeneral_nombreEmpresa"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_direccionEmpresa
        {
            get
            {
                return ((string)(this["pGeneral_direccionEmpresa"]));
            }
            set
            {
                this["pGeneral_direccionEmpresa"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_telefonoEmpresa
        {
            get
            {
                return ((string)(this["pGeneral_telefonoEmpresa"]));
            }
            set
            {
                this["pGeneral_telefonoEmpresa"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_razonSocial
        {
            get
            {
                return ((string)(this["pGeneral_razonSocial"]));
            }
            set
            {
                this["pGeneral_razonSocial"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_ingresosBrutos
        {
            get
            {
                return ((string)(this["pGeneral_ingresosBrutos"]));
            }
            set
            {
                this["pGeneral_ingresosBrutos"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_pathLogotipo
        {
            get
            {
                return ((string)(this["pGeneral_pathLogotipo"]));
            }
            set
            {
                this["pGeneral_pathLogotipo"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pGeneral_inicioActividades
        {
            get
            {
                return ((string)(this["pGeneral_inicioActividades"]));
            }
            set
            {
                this["pGeneral_inicioActividades"] = value;
            }
        }

    }
}
