//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int nroPedido { get; set; }
        public Nullable<System.DateTime> fechaPed { get; set; }
        public Nullable<double> montoTotalPed { get; set; }
        public string obsPed { get; set; }
        public Nullable<int> codTipoPedido { get; set; }
        public string dniPers { get; set; }
    
        public virtual personas personas { get; set; }
        public virtual tipo_pedidos tipo_pedidos { get; set; }
    }
}
