//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            this.pedidos = new HashSet<pedidos>();
            this.rol_pers = new HashSet<rol_pers>();
        }
    
        public string dniPers { get; set; }
        public string cuitPers { get; set; }
        public string nombrePers { get; set; }
        public string apellidoPers { get; set; }
        public string direccPers { get; set; }
        public string ciudadPers { get; set; }
        public string provinciaPers { get; set; }
        public string codigoPostalPers { get; set; }
        public string obsPers { get; set; }
        public string usuarioPers { get; set; }
        public string contraseniaPers { get; set; }
        public string razonSocialProv { get; set; }
    
        public virtual mail_pers mail_pers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos> pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_pers> rol_pers { get; set; }
        public virtual tel_pers tel_pers { get; set; }
    }
}
