//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class valor_ven
    {
        public string codigoOriginalArt { get; set; }
        public string codigoArProveedor { get; set; }
        public System.DateTime fechaVal { get; set; }
        public double valorVen { get; set; }
    
        public virtual valor_ven valor_ven1 { get; set; }
        public virtual valor_ven valor_ven2 { get; set; }
    }
}
