//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ped_art_prov
    {
        public int nroPedido { get; set; }
        public string codigoArProveedor { get; set; }
        public string codigoOriginalAr { get; set; }
        public Nullable<int> cantidadArticulos { get; set; }
        public Nullable<double> valorParcial { get; set; }
    
        public virtual art_prov art_prov { get; set; }
    }
}
