//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedores()
        {
            this.art_prov = new HashSet<art_prov>();
        }
    
        public string razonSocialProv { get; set; }
        public string cuitProv { get; set; }
        public string direccionProv { get; set; }
        public string ciudadProv { get; set; }
        public string provinciaProv { get; set; }
        public string codigoPostalProv { get; set; }
        public string obsProv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<art_prov> art_prov { get; set; }
        public virtual mail_prov mail_prov { get; set; }
        public virtual tel_prov tel_prov { get; set; }
    }
}
