//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class valor_com
    {
        public string codigoOriginalArt { get; set; }
        public string codigoArProveedor { get; set; }
        public System.DateTime fechaVal { get; set; }
        public double valorCom { get; set; }
    
        public virtual valor_com valor_com1 { get; set; }
        public virtual valor_com valor_com2 { get; set; }
    }
}
